# Importing Libraries

In [1]:
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Importing Data using Pandas

In [2]:
df=pd.read_csv('collections.csv')
df.head()

pid  cid    time  indexFinger.X  indexFinger.Y  indexFinger.Z    hand.X  \
0    1    0  5.4313       0.027433       0.933357       0.349472  0.051850   
1    1    1  2.2326       0.222986       0.736402       0.328534  0.187769   
2    1    2  2.0435       0.030588       0.928704       0.367933  0.047651   
3    1    3  2.2542       0.186396       1.095677       0.252556  0.162737   
4    1    4  2.9104      -0.078487       1.057077       0.297237 -0.035096   

     hand.Y    hand.Z  forearm.X  ...  upperArmO.Z  rightShoulderO.X  \
0  0.895263  0.245369   0.086555  ...    -0.190203         -0.002935   
1  0.745385  0.221451   0.185908  ...    -0.314556         -0.022165   
2  0.889884  0.263894   0.085004  ...    -0.199041          0.013664   
3  1.012611  0.179633   0.164037  ...    -0.088130          0.046375   
4  0.984453  0.222878   0.021838  ...    -0.126742          0.058604   

   rightShoulderO.Y  rightShoulderO.Z    hmdO.X    hmdO.Y    hmdO.Z  \
0          0.366088          0.037051 -0.048971 -0.007790  0.010917   
1          0.490407         -0.060302 -0.105206 -0.129680  0.030141   
2          0.296288          0.037047 -0.074365  0.019567  0.009265   
3         -0.336142         -0.036984  0.022072 -0.152640 -0.007073   
4         -0.164009         -0.044563 -0.009818  0.138230 -0.006361   

   leftShoulderO.X  leftShoulderO.Y  leftShoulderO.Z  
0        -0.124852        -0.403729        -0.102975  
1        -0.137058        -0.335889        -0.093367  
2        -0.119852        -0.448962        -0.108039  
3        -0.115766        -0.410206        -0.082019  
4        -0.093350        -0.571542        -0.104874  

[5 rows x 45 columns]

In [3]:
target=pd.read_csv('targets.csv')
target.head()

cid  pid  target.X  target.Y  target.Z
0    0    1         0      1.49       1.5
1    1    1         1      0.49       1.5
2    2    1         0      1.49       1.5
3    3    1         1      2.49       1.5
4    4    1        -1      2.49       2.5

# Merging the two tables

In [4]:
df_merged=pd.merge(df,target,on=['pid','cid'])

In [5]:
df_merged

pid  cid    time  indexFinger.X  indexFinger.Y  indexFinger.Z    hand.X  \
0       1    0  5.4313       0.027433       0.933357       0.349472  0.051850   
1       1    1  2.2326       0.222986       0.736402       0.328534  0.187769   
2       1    2  2.0435       0.030588       0.928704       0.367933  0.047651   
3       1    3  2.2542       0.186396       1.095677       0.252556  0.162737   
4       1    4  2.9104      -0.078487       1.057077       0.297237 -0.035096   
...   ...  ...     ...            ...            ...            ...       ...   
1750   13  130  1.2670       0.127980       0.805490       0.375001  0.113389   
1751   13  131  1.2880      -0.103204       1.039377       0.282554 -0.056924   
1752   13  132  1.1210      -0.002564       1.032143       0.314632  0.020999   
1753   13  133  2.6650      -0.135052       1.037089       0.304865 -0.081800   
1754   13  134  1.0110      -0.005458       0.922803       0.363993  0.021246   

        hand.Y    hand.Z  forearm.X  ...  rightShoulderO.Z    hmdO.X  \
0     0.895263  0.245369   0.086555  ...          0.037051 -0.048971   
1     0.745385  0.221451   0.185908  ...         -0.060302 -0.105206   
2     0.889884  0.263894   0.085004  ...          0.037047 -0.074365   
3     1.012611  0.179633   0.164037  ...         -0.036984  0.022072   
4     0.984453  0.222878   0.021838  ...         -0.044563 -0.009818   
...        ...       ...        ...  ...               ...       ...   
1750  0.805587  0.258079   0.109436  ...         -0.138837 -0.075221   
1751  0.966288  0.205039  -0.010729  ...         -0.161561  0.029986   
1752  0.965270  0.220223   0.043993  ...         -0.165613  0.002959   
1753  0.974012  0.219963  -0.043241  ...         -0.173299 -0.011723   
1754  0.886517  0.254696   0.040414  ...         -0.160074 -0.055674   

        hmdO.Y    hmdO.Z  leftShoulderO.X  leftShoulderO.Y  leftShoulderO.Z  \
0    -0.007790  0.010917        -0.124852        -0.403729        -0.102975   
1    -0.129680  0.030141        -0.137058        -0.335889        -0.093367   
2     0.019567  0.009265        -0.119852        -0.448962        -0.108039   
3    -0.152640 -0.007073        -0.115766        -0.410206        -0.082019   
4     0.138230 -0.006361        -0.093350        -0.571542        -0.104874   
...        ...       ...              ...              ...              ...   
1750 -0.126655 -0.040035         0.103612         0.450116         0.089577   
1751  0.070127  0.004378         0.103444         0.585615         0.087713   
1752 -0.038942 -0.038431         0.107274         0.528982         0.084923   
1753  0.102930 -0.038536         0.113416         0.573764         0.106144   
1754 -0.049702 -0.048589         0.105635         0.508864         0.082404   

      target.X  target.Y  target.Z  
0            0      1.49       1.5  
1            1      0.49       1.5  
2            0      1.49       1.5  
3            1      2.49       1.5  
4           -1      2.49       2.5  
...        ...       ...       ...  
1750         1      0.49       3.5  
1751        -1      2.49       3.5  
1752         0      2.49       3.5  
1753        -1      2.49       3.5  
1754         0      1.49       3.5  

[1755 rows x 48 columns]

In [6]:
df_merged.columns

Index(['pid', 'cid', 'time', 'indexFinger.X', 'indexFinger.Y', 'indexFinger.Z',
       'hand.X', 'hand.Y', 'hand.Z', 'forearm.X', 'forearm.Y', 'forearm.Z',
       'upperArm.X', 'upperArm.Y', 'upperArm.Z', 'rightShoulder.X',
       'rightShoulder.Y', 'rightShoulder.Z', 'hmd.X', 'hmd.Y', 'hmd.Z',
       'leftShoulder.X', 'leftShoulder.Y', 'leftShoulder.Z', 'indexFingerO.X',
       'indexFingerO.Y', 'indexFingerO.Z', 'handO.X', 'handO.Y', 'handO.Z',
       'forearmO.X', 'forearmO.Y', 'forearmO.Z', 'upperArmO.X', 'upperArmO.Y',
       'upperArmO.Z', 'rightShoulderO.X', 'rightShoulderO.Y',
       'rightShoulderO.Z', 'hmdO.X', 'hmdO.Y', 'hmdO.Z', 'leftShoulderO.X',
       'leftShoulderO.Y', 'leftShoulderO.Z', 'target.X', 'target.Y',
       'target.Z'],
      dtype='object')

## Separating data as per Y coordinate

In [7]:
df_features=df_merged[['indexFinger.X', 'indexFinger.Y', 'indexFinger.Z']]
y=pd.DataFrame(df_merged['target.Y'])

In [8]:
y

target.Y
0         1.49
1         0.49
2         1.49
3         2.49
4         2.49
...        ...
1750      0.49
1751      2.49
1752      2.49
1753      2.49
1754      1.49

[1755 rows x 1 columns]

## Separating data as per Z coordinate

In [9]:
y2=pd.DataFrame(df_merged['target.Z'])

# Scaling the data 

In [10]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler=MinMaxScaler()

In [11]:
df_features_scaled=scaler.fit_transform(df_features)

In [12]:
y_scaled=scaler.fit_transform(y).reshape(-1,1)

In [13]:
y2_scaled=scaler.fit_transform(y2).reshape(-1,1)

In [14]:
df_features_scaled

array([[0.49733932, 0.64155304, 0.81455007],
       [0.85237446, 0.30106612, 0.7673059 ],
       [0.50306736, 0.63350915, 0.85620517],
       ...,
       [0.44287844, 0.81232983, 0.73593765],
       [0.2023406 , 0.82088025, 0.71389955],
       [0.43762425, 0.62330777, 0.84731502]])

In [15]:
y_scaled

array([[0.5],
       [0. ],
       [0.5],
       ...,
       [1. ],
       [1. ],
       [0.5]])

In [16]:
y2_scaled

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

# Creating X and Y by the dataset

In [17]:
x=pd.DataFrame(data=df_features_scaled,columns=['Input1','Input2','Input3'])
Y=pd.DataFrame(data=y_scaled,columns=['Y-coordinate'])

In [18]:
Y2=pd.DataFrame(data=y2_scaled,columns=['Z-Coordinate'])

# Creating dummy variables

In [19]:
dummies=pd.get_dummies(Y['Y-coordinate'])

In [20]:
dummies.rename(columns={0.0:'low',0.5:'middle',1.0:'high'},inplace=True)

In [21]:
dummies

low  middle  high
0       0       1     0
1       1       0     0
2       0       1     0
3       0       0     1
4       0       0     1
...   ...     ...   ...
1750    1       0     0
1751    0       0     1
1752    0       0     1
1753    0       0     1
1754    0       1     0

[1755 rows x 3 columns]

In [22]:
dummies2=pd.get_dummies(Y2['Z-Coordinate'])

In [23]:
dummies2.rename(columns={0.0:'close',0.5:'middle',1.0:'far'},inplace=True)

## Segregating Data based on Y coordiinates

In [24]:
df_top=df_merged[df_merged['target.Y']==2.49]

In [25]:
df_middle=df_merged[df_merged['target.Y']==1.49]

In [26]:
df_below=df_merged[df_merged['target.Y']==0.49]

## Creating the Models

In [27]:
model1=GaussianNB()

In [28]:
model2=KNeighborsClassifier(n_neighbors=1)

In [29]:
model3=SVC()

In [30]:
model4=RandomForestClassifier()

## Testing accuracy by separating data as per position of points according to height

# Naive Bayes

### Data Points at the bottom

In [31]:
cross_val_score(model1,x,dummies['low'],cv=3).mean()    

0.9760683760683762

### Data Points at the middle

In [32]:
cross_val_score(model1,x,dummies['middle'],cv=3).mean()

0.9225071225071225

### Data Points at the high

In [33]:
cross_val_score(model1,x,dummies['high'],cv=3).mean()

0.9908831908831909

# KNN

### Data Points at the bottom


In [34]:
cross_val_score(model2,x,dummies['low'],cv=3).mean()

0.978917378917379

### Data Points at the middle

In [35]:
cross_val_score(model2,x,dummies['middle'],cv=3).mean()

0.9783475783475785

### Data Points at the high

In [36]:
cross_val_score(model2,x,dummies['high'],cv=3).mean()

0.9948717948717949

# SVM

### Data Points at the bottom


In [37]:
cross_val_score(model3,x,dummies['low'],cv=3).mean()

0.9800569800569802

### Data Points at the middle

In [38]:
cross_val_score(model3,x,dummies['middle'],cv=3).mean()

0.9772079772079773

### Data Points at the high

In [39]:
cross_val_score(model3,x,dummies['high'],cv=3).mean()

0.9965811965811966

# Random Forest Classifier

### Data Points at the bottom


In [40]:
cross_val_score(model4,x,dummies['low'],cv=3).mean()

0.9766381766381768

### Data Points at the middle

In [41]:
cross_val_score(model4,x,dummies['middle'],cv=3).mean()

0.9720797720797721

### Data Points at the high

In [42]:
cross_val_score(model4,x,dummies['high'],cv=3).mean()

0.9948717948717949

### As we can see from the above results, we can see that the accuracy is high for the higher points, it decreases as we come at the middle and increases and becomes maximum at the bottom points.

## Testing accuracy by separating data as per position of points according to height

# Naive Bayes

### Data Points which are near

In [55]:
cross_val_score(model1,x,dummies2['close'],cv=3).mean()    

0.776068376068376

### Data Points which are in the middle

In [44]:
cross_val_score(model1,x,dummies2['middle'],cv=3).mean()  

0.6666666666666666

### Data Points which are far

In [45]:
cross_val_score(model1,x,dummies2['far'],cv=3).mean()  

0.7162393162393164

## KNN

### Data Points which are near

In [46]:
cross_val_score(model2,x,dummies2['close'],cv=3).mean()    

0.7504273504273504

### Data Points which are in the middle

In [47]:
cross_val_score(model2,x,dummies2['middle'],cv=3).mean()    

0.5504273504273505

### Data Points which are far

In [48]:
cross_val_score(model2,x,dummies2['far'],cv=3).mean()    

0.7025641025641026

## SVM

### Data Points which are near

In [49]:
cross_val_score(model3,x,dummies2['close'],cv=5).mean()  

0.8148148148148149

### Data Points which are in the middle

In [50]:
cross_val_score(model3,x,dummies2['middle'],cv=5).mean()  

0.6666666666666666

### Data Points which are far

In [51]:
cross_val_score(model3,x,dummies2['far'],cv=5).mean()  

0.7407407407407407

## Random Forest

### Data Points which are near

In [52]:
cross_val_score(model4,x,dummies2['close'],cv=5).mean()  

0.8005698005698006

### Data Points which are in the middle

In [53]:
cross_val_score(model4,x,dummies2['middle'],cv=5).mean()  

0.6005698005698006

### Data Points which are far

In [54]:
cross_val_score(model4,x,dummies2['far'],cv=5).mean()  

0.7076923076923076

## Inference

So as we can see through the above results, the accuracy is highest when the data point in closer, it is lowest when in the middle and also low as compared to the closer ones when it is far away